#########################################
# BIDIRECTIONAL RECURRENT NEURAL NETWORK#
#            PARAMETER FILE             #
#########################################

# RNN ARCHITECTURE
batch_size: 32
cell_type: LSTM
learning_rate: 0.01
layer_size: 51
optimizer: adadelta
num_layers: 3
read_length: 5000
input_size: 51
num_classes: 5
num_epochs: 6
dropout_keep_prob: 0.5
training_iterations: 1000
adaptive_positive_weighting: true
simulate_on_the_fly: false
additional_plotting: true
min_content_percentage: 0.01
